<div class="row">
	<div class="col-sm-12">
		<div class="page-title-box">
			<div class="btn-group float-right">
				<ol class="breadcrumb hide-phone p-0 m-0">
					<li class="breadcrumb-item">
						<a href="<?php echo site_url('dashboard'); ?>"><?php echo _('Inicio') ?></a>
					</li>
					<li class="breadcrumb-item">
						<a href="<?php echo site_url('dashboard/catalogos/'); ?>"><?php echo _('Catalogos') ?></a>
					</li>
					<li class="breadcrumb-item active">
						<?php echo _('Semaforización') ?>
					</li>
				</ol>
			</div>
			<h4 class="page-title"><?php echo _('Semaforización') ?></h4>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-12">
		<div class="card m-b-30">
			<div class="card-body">
				<h4><?php echo _('Semaforización') ?></h4>
				<hr>
				<div class="m-b-30">
					<button data-toggle="modal" data-target="#nuevo" type="button" class="btn btn-success waves-effect waves-light m-r-10 m-b-10 pull-right"><?php echo _('Nuevo registro') ?></button>
				</div>
				<br>
				<hr>
				<table id="grid-data-api" class="table table-condensed table-hover table-striped tabla-ajax" data-column-aling="center" data-url="<?php echo site_url('ajax/sistema/semaforizacion'); ?>" data-url-editar="<?php echo site_url('ajax/sistema/semaforizacion/consulta'); ?>" data-url-borrar="<?php echo site_url('ajax/sistema/semaforizacion/eliminar'); ?>">
					<thead>
						<tr>
							<th data-column-id="id" data-header-align="center" data-align="center" data-a="ams" data-type="numeric">id</th>
							<th data-column-id="Inicial" data-align="center"><?php echo _('Inicial') ?></th>
							<th data-column-id="Final" data-align="center"><?php echo _('Final') ?></th>
							<th data-formatter="color" data-sortable="false" data-align="center" data-column-id="Color"><?php echo _('Color')  ?></th>
							<th data-formatter="acciones" data-align="center" data-sortable="false"><?php echo _('Acciones') ?></th>
						</tr>
					</thead>
				</table>
				<a href="<?php echo site_url('dashboard/catalogos/enfoques/nuevo'); ?>">
				</a>
			</div>
		</div>
	</div>
	<!-- end col -->
</div>
<!-- end row -->
<div class="modal fade show modal-detalles" id="nuevo" tabindex="-1" role="dialog">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-body">
				<h6><?php echo _('Nuevo registro') ?></h6>
				<hr>
				<form class="form-ajax" data-url="sistema/semaforizacion/nuevo" data-parsley-validate>
					<div class="form-group row">
						<label class="col-sm-2 col-form-label required"><?php echo _('Inicial') ?></label>
						<div class="input-group mt-2 col-sm-8">
							<div class="input-group-prepend">
								<span class="input-group-text"><i class="fas fa-percent"></i></span>
							</div>
							<input type="text" id="example-input3-group1" required="" name="datos[Inicial]" value="" class="form-control" placeholder="0">
							<div class="input-group-append">
							</div>
						</div>
					</div>
					<div class="form-group row">
						<label class="col-sm-2 col-form-label required"><?php echo _('Final') ?></label>
						<div class="input-group mt-2 col-sm-8">
							<div class="input-group-prepend">
								<span class="input-group-text"><i class="fas fa-percent"></i></span>
							</div>
							<input type="text" id="example-input3-group1"  required="" name="datos[Final]" class="form-control" placeholder="100">
							<div class="input-group-append">
							</div>
						</div>
					</div>
					<div class="form-group row">
						<label class="col-sm-2 col-form-label required"><?php echo _('Color') ?></label>
						<div class="col-sm-8">
							<input class="form-control" type="color" name="datos[Color]" value="#67a8e4" id="example-color-input">
						</div>
					</div>
					<div class="modal-footer">
						<button type="submit" class="btn btn-primary float-right"><?php echo _('Guardar') ?></button>
						<button type="button" class="btn btn-default" data-dismiss="modal"><?php echo _('Cerrar') ?></button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

<div class="modal fade show modal-detalles" id="Editar" tabindex="-1" role="dialog">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-body">
				<h6><?php echo _('Editar semaforización') ?></h6>
				<hr>
				<form class="form-ajax" data-url="sistema/semaforizacion/editar" data-parsley-validate>
					<div class="form-group row">
						<label class="col-sm-2 col-form-label required"><?php echo _('Inicial') ?></label>
						<div class="input-group mt-2 col-sm-8">
							<div class="input-group-prepend">
								<span class="input-group-text"><i class="fas fa-percent"></i></span>
							</div>
							<input type="text" id="example-input3-group1" required="" name="datos[Inicial]" :value="datos.Inicial" class="form-control" placeholder="0">
							<div class="input-group-append">
							</div>
						</div>
					</div>
					<div class="form-group row">
						<label class="col-sm-2 col-form-label required"><?php echo _('Final') ?></label>
						<div class="input-group mt-2 col-sm-8">
							<div class="input-group-prepend">
								<span class="input-group-text"><i class="fas fa-percent"></i></span>
							</div>
							<input type="text" id="example-input3-group1"  required="" name="datos[Final]"  class="form-control" placeholder="100" :value="datos.Final">
							<div class="input-group-append">
							</div>
						</div>
					</div>
					<div class="form-group row">
						<label class="col-sm-2 col-form-label required"><?php echo _('Color') ?></label>
						<div class="col-sm-8">
							<input class="form-control" type="color" name="datos[Color]"  id="example-color-input" :value="datos.Color">
						</div>
					</div>
					<div class="modal-footer">
						<button type="submit" class="btn btn-primary float-right"><?php echo _('Guardar') ?></button>
						<button type="button" class="btn btn-default" data-dismiss="modal"><?php echo _('Cerrar') ?></button>
					</div>
					<input type="hidden" name="id" :value="datos.id" />
				</form>
			</div>
		</div>
	</div>
</div>
