<div class="row">
	<div class="col-sm-12">
		<div class="page-title-box">
			<div class="btn-group float-right">
				<ol class="breadcrumb hide-phone p-0 m-0">
					<li class="breadcrumb-item">
						<a href="<?= site_url('dashboard') ?>">
							<?= _('Inicio')?></a>
					</li>
					<li class="breadcrumb-item">
						<a href="<?= site_url('dashboard/refile/') ?>">
							<?= _('Campañas REFILE')?></a>
					</li>
					<li class="breadcrumb-item active">
						<?= _('Administración de Campaña')?>
					</li>
				</ol>
			</div>
			<h4 class="page-title">
				<?= _('Administración de Campaña')?>
			</h4>
		</div>
	</div>
</div>


<div class="row">
	<div class="col-12">
		<div class="card">
			<div class="card-body">
				<h4 class="card-title">
					<?= _('Administración de Campaña')?>
				</h4>
				<hr>
				<!-- <div class="m-b-30">
					<button class="btn btn-success waves-effect waves-light m-r-10 m-b-10 pull-right" data-toggle="modal" data-target="#creapdf">
						<i class="fas fa-plus-circle"></i>
						<?php echo _('Agregar') ?>
					</button>
				</div> -->
				<br>
				<hr>
				<!-- <table class="table table-condensed table-hover table-striped tabla-ajax"> -->
				<table class="table table-condensed table-hover table-striped">
					<thead>
						<tr>
							<th data-column-id="id" data-type="numeric">id</th>
							<th data-column-id="Nombre_Campana">
								<?php echo _('Nombre Campaña') ?>
							</th>
							<th data-column-id="Fecha_inicio">
								<?php echo _('Fecha Inicio') ?>
							</th>
							<th data-column-id="Mercado">
								<?php echo _('Mercado') ?>
							</th>
							<th data-column-id="Detalles de variables">
								<?php echo _('Detalles de Variables') ?>
							</th>
							<th data-column-id="Estatus">
								<?php echo _('Estatus') ?>
							</th>
							<th>
								<?php echo _('Acciones') ?>
							</th>
						</tr>
					</thead>
					<tbody>

							<tr>
								<td>001</td>
								<td>Nombre negocio 001</td>
								<td>27/Oct</td>
								<td>1500</td>
								<td>
									<a href="#" class="buttontable">
										<button type="button" class="btn btn-info waves-effect waves-light">	<i class="far fa-file-alt"></i></button>
									</a>
								</td>
								<td>
									<div class="iconandtext">
										<i class="fas fa-envelope"></i>Enviado
									</div>
								</td>
								<td>
									<a href="#" class="buttontable" data-toggle="modal" data-target="#creapdf"></a>
								</td>
							</tr>

							<tr>
								<td>001</td>
								<td>Nombre negocio 001</td>
								<td>27/Oct</td>
								<td>1500</td>
								<td>
									<a href="#" class="buttontable">
										<button type="button" class="btn btn-info waves-effect waves-light">	<i class="far fa-file-alt"></i></button>
									</a>
								</td>
								<td>
									<div class="iconandtext">
										<i class="fas fa-envelope-open"></i>Preparando
									</div>
								</td>
								<td>
									<!-- <a href="#" class="buttontable" data-toggle="modal" data-target="#creapdf"><i class="fas fa-plus-circle"></i></a> -->
									<a href="#" class="buttontable">
										<button type="button" class="btn btn-success waves-effect waves-light" data-toggle="modal" data-target="#creapdf">
												<i class="fas fa-plus-circle"></i>
										</button>
									</a>
									<a href="#" class="buttontable">
										<button type="button" class="btn btn-info waves-effect waves-light">	<i class="far fa-file-alt"></i></button>
									</a>
									<a href="#" class="buttontable">
										<button type="button" class="btn btn-info waves-effect waves-light">	<i class="far fa-file-alt"></i></button>
									</a>
									<a href="#" class="buttontable">
										<button type="button" class="btn btn-info waves-effect waves-light">	<i class="far fa-file-alt"></i></button>
									</a>
								</td>
							</tr>

							<tr>
								<td>001</td>
								<td>Nombre negocio 001</td>
								<td>27/Oct</td>
								<td>1500</td>
								<td>
									<a href="#" class="buttontable">
										<button type="button" class="btn btn-info waves-effect waves-light">	<i class="far fa-file-alt"></i></button>
									</a>
								</td>

								<td>
									<div class="iconandtext">
										<i class="fas fa-file"></i>
										Por enviar
									</div>
								</td>
								<td>
									<!-- <a href="#" class="buttontable" data-toggle="modal" data-target="#creapdf"><i class="fas fa-plus-circle"></i></a> -->
								</td>
							</tr>

						</tbody>
				</table>
			</div>
		</div>
	</div>
</div>


<div id="creapdf" class="modal fade" role="dialog">
		<div class="modal-dialog modal-lg modal-xxl">
			<!-- Modal content-->
			<div class="modal-content">
				<div class="modal-header">
					<h4 class="modal-title">
						<?=_('Configuración de campaña')?> "Lorem Ipsum"
					</h4>
					<button type="button" class="close" data-dismiss="modal">&times;</button>
				</div>
				<div class="modal-body">
					<div class="detallesCampana scrollmodal">
						<div class="textcampana">
							<div class="form-group">
								<label for="Nombre_Campana">
									<label class="col-form-label required">
										<?php echo _('Nombre') ?>
									</label>
								</label>
	  						<input type="text" class="form-control" required name="">
							</div>

							<div class="form-group">
								<label for="Fecha_inicio">
									<label class="col-form-label required">
										<?php echo _('Fecha de inicio') ?>
									</label>
								</label>
								<?php $today = getdate();
									$mes = $today['mon'];
									$dia = $today['mday'];
									if ($mes <=9) {
										$mes = "0" . $mes;
									}
									if ($dia <=9){
										$dia = "0" . $dia;
									}

								?>
								  <input class="form-control" type="date" value="<?= $today['year'];?>-<?= $mes;?>-<?= $dia;?>">
							</div>

							<div class="form-group">
								<label for="Mercado">
									<label class="col-form-label required">
										<?php echo _('Mercado') ?>
									</label>
								</label>
	  						<input type="number" class="form-control" required name="">
							</div>

							<div class="form-group">
								<label for="Asunto">
									<label class="col-form-label required">
										<?php echo _('Asunto') ?>
									</label>
								</label>
	  						<input type="text" class="form-control" required name="">
							</div>

							<div class="form-group">
								<label for="Imagen">
									<label class="col-form-label required">
										<?php echo _('Imagen') ?>
									</label>
								</label>
								<input type="file" class="dropify text-center center-block file-upload" required>
							</div>

							<div class="form-group">
								<label for="Texto">
									<label class="col-form-label required">
										<?php echo _('Texto') ?>
									</label>
								</label>
								<div id="summernote"></div>
							</div>



						</div>

						<div class="pdfcampana">

						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
