<div class="row">
	<div class="col-sm-12">
		<div class="page-title-box">
			<div class="btn-group float-right">
				<ol class="breadcrumb hide-phone p-0 m-0">
					<li class="breadcrumb-item">
						<a href="<?php echo site_url('dashboard'); ?>"><?php echo _('Inicio') ?></a>
					</li>
					<li class="breadcrumb-item">
						<a href="<?php echo site_url('dashboard/catalogos/'); ?>"><?php echo _('Catalogos') ?></a>
					</li>
					<li class="breadcrumb-item active">
						<?php echo _('Membresia') ?>
					</li>
				</ol>
			</div>
			<h4 class="page-title"><?php echo _('Planes de Membresia') ?></h4>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-12">
		<div class="card m-b-30">
			<div class="card-body">
				<h4><?php echo _('Planes Membresia') ?></h4>
				<hr>
				<div class="m-b-30">
					<button data-toggle="modal" data-target="#nuevo" type="button" class="btn btn-success waves-effect waves-light m-r-10 m-b-10 pull-right"><?php echo _('Nuevo registro') ?></button>
				</div>
				<br>
				<hr>
				<table class="table table-condensed table-hover table-striped tabla-ajax" data-url="<?php echo site_url('ajax/sistema/membresia'); ?>" data-url-editar="<?php echo site_url('ajax/sistema/membresia/consulta'); ?>" data-url-borrar="<?php echo site_url('ajax/sistema/membresia/eliminar'); ?>">
					<thead>
						<tr>
							<th data-column-id="id" data-type="numeric">id</th>
							<th data-column-id="Nombre"><?php echo _('Nombre') ?></th>
							<th data-column-id="Monto" data-formatter="money"><?php echo _('Monto') ?></th>
							<th data-column-id="PagoDiferido"><?php echo _('Pago diferido') ?></th>
							<th data-column-id="LimiteClientes"><?php echo _('Limite de clientes') ?></th>
							<th data-column-id="LimiteEncuestas"><?php echo _('Limite Encuestas') ?></th>
							<th data-column-id="Duracion"><?php echo _('Duracion') ?></th>
							<th data-formatter="acciones" data-sortable="false"><?php echo _('Acciones') ?></th>
						</tr>
					</thead>
				</table>
				<a href="<?php echo site_url('dashboard/catalogos/enfoques/nuevo'); ?>">
				</a>
			</div>
		</div>
	</div>
	<!-- end col -->
</div>
<!-- end row -->
<div class="modal fade show modal-detalles" id="nuevo" tabindex="-1" role="dialog" >
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-body">
				<h6><?php echo _('Nuevo registro') ?></h6>
				<hr>
				<form class="form-ajax" data-url="sistema/membresia/nuevo" data-parsley-validate>
					<div class="form-group row">
						<label class="col-sm-2 col-form-label required"><?php echo _('Nombre') ?></label>
						<div class="col-sm-8">
							<input class="form-control" placeholder="" required="" name="datos[nombre]">
						</div>
					</div>
					<div class="form-group row">
						<label class="col-sm-2 col-form-label required"><?php echo _('Monto') ?></label>
						<div class="input-group mt-2 col-sm-8">
							<div class="input-group-prepend">
								<span class="input-group-text"><i class="fa fa-dollar"></i></span>
							</div>
							<input type="text" id="example-input3-group1" required="" name="datos[monto]" class="form-control" placeholder="">
							<div class="input-group-append">
								<span class="input-group-text">.00</span>
							</div>
						</div>
					</div>
					<div class="form-group row">
						<label class="col-sm-2 col-form-label required"><?php echo _('Pago Diferido') ?></label>
						<div class="col-sm-8">
							<input class="form-control" placeholder="" required="" name="datos[diferido]">
						</div>
					</div>
					<div class="form-group row">
						<label class="col-sm-2 col-form-label required"><?php echo _('Limite de clientes') ?></label>
						<div class="col-sm-8">
							<input class="form-control" placeholder="" required="" name="datos[clientes]">
						</div>
					</div>
					<div class="form-group row">
						<label class="col-sm-2 col-form-label required"><?php echo _('Limite de encuestas') ?></label>
						<div class="col-sm-8">
							<input class="form-control" placeholder="" required="" name="datos[encuestas]">
						</div>
					</div>
					<div class="form-group row">
						<label class="col-sm-2 col-form-label required"><?php echo _('Duración') ?></label>
						<div class="col-sm-8">
							<input class="form-control" placeholder="" required="" name="datos[duracion]">
						</div>
					</div>
					<div class="modal-footer">
						<button type="submit" class="btn btn-primary float-right"><?php echo _('Guardar') ?></button>
						<button type="button" class="btn btn-default" data-dismiss="modal"><?php echo _('Cerrar') ?></button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

<div class="modal fade show modal-detalles" id="Editar" tabindex="-1" role="dialog">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-body">
				<h6><?php echo _('Editar plan membresia') ?></h6>
				<hr>
				<form class="form-ajax" data-url="sistema/membresia/editar" data-parsley-validate>
					<div class="form-group row">
						<label class="col-sm-2 col-form-label required"><?php echo _('Nombre') ?></label>
						<div class="col-sm-8">
							<input class="form-control" placeholder="" required="" name="datos[Nombre]" :value="datos.id">
						</div>
					</div>
					<div class="form-group row">
						<label class="col-sm-2 col-form-label required"><?php echo _('Monto') ?></label>
						<div class="input-group mt-2 col-sm-8">
							<div class="input-group-prepend">
								<span class="input-group-text"><i class="fa fa-dollar"></i></span>
							</div>
							<input type="text" id="example-input3-group1" required="" name="datos[Monto]" :value="datos.Monto" class="form-control" placeholder="..">
							<div class="input-group-append">
								<span class="input-group-text">.00</span>
							</div>
						</div>
					</div>
					<div class="form-group row">
						<label class="col-sm-2 col-form-label required"><?php echo _('Pago Diferido') ?></label>
						<div class="col-sm-8">
							<input class="form-control" placeholder="" required="" name="datos[Diferido]" :value="datos.Diferido">
						</div>
					</div>
					<div class="form-group row">
						<label class="col-sm-2 col-form-label required"><?php echo _('Limite de clientes') ?></label>
						<div class="col-sm-8">
							<input class="form-control" placeholder="" required="" name="datos[LimiteClientes]" :value="datos.LimiteClientes">
						</div>
					</div>
					<div class="form-group row">
						<label class="col-sm-2 col-form-label required"><?php echo _('Limite de encuestas') ?></label>
						<div class="col-sm-8">
							<input class="form-control" placeholder="" required="" name="datos[LimiteEncuestas]" :value="datos.LimiteEncuestas">
						</div>
					</div>
					<div class="form-group row">
						<label class="col-sm-2 col-form-label required"><?php echo _('Duración') ?></label>
						<div class="col-sm-8">
							<input class="form-control" placeholder="" required="" name="datos[Duracion]" :value="datos.Duracion">
						</div>
					</div>
					<div class="modal-footer">
						<button type="submit" class="btn btn-primary float-right"><?php echo _('Guardar') ?></button>
						<button type="button" class="btn btn-default" data-dismiss="modal"><?php echo _('Cerrar') ?></button>
					</div>
					<input type="hidden" name="id" :value="datos.id" />
				</form>
			</div>
		</div>
	</div>
</div>
