<div class="row">
	<div class="col-sm-12">
		<div class="page-title-box">
			<div class="btn-group float-right">
				<ol class="breadcrumb hide-phone p-0 m-0">
					<li class="breadcrumb-item">
						<a href="<?= site_url('dashboard') ?>">
							<?= _('Inicio')?></a>
					</li>
					<li class="breadcrumb-item">
						<a href="<?= site_url('dashboard/campanas/') ?>">
							<?= _('Campañas')?></a>
					</li>
					<li class="breadcrumb-item active">
						<?= _('Campañas de satisfacción')?>
					</li>
				</ol>
			</div>
			<h4 class="page-title">
				<?= _('Campañas de satisfacción')?>
			</h4>
		</div>
	</div>
</div>


<div class="row">
	<div class="col-12">
		<div class="card">
			<div class="card-body">

				<h4 class="card-title">
					<?php echo _('Campañas de satisfacción') ?>
				</h4>
				<hr>
				<div class="m-b-30">
					<button class="btn btn-success waves-effect waves-light m-r-10 m-b-10 pull-right" data-toggle="modal" data-target="#nuevaCamp">
						<i class="fas fa-plus-circle"></i>
						<?php echo _('Agregar') ?>
					</button>
				</div>
				<br>
				<hr>

				<table class="table table-condensed table-hover table-striped tabla-ajax" data-url="<?= site_url('ajax/sistema/campanas-satisfaccion'); ?>" data-url-editar="#" data-url-borrar="#">
					<thead>
						<tr>
							<th data-column-id="id" data-align="center" data-type="numeric"><span>id</span></th>
							<th data-column-id="Nombre" data-align="center"><span><?= _('Campaña') ?></span></th>
							<th data-column-id="unidades_negocio" data-align="center"><span><?= _('Unidad de Negocio') ?></span></th>
							<th data-column-id="FechaFin" data-align="center"><span><?= _('Fecha Fin') ?></span></th>
							<th data-column-id="Tipo" data-align="center"><span><?= _('Tipo de Campaña') ?></span></th>
							<th data-column-id="Cantidad" data-align="center"><span><?= _('Num. Encuenstas') ?></span></th>
              <th data-column-id="MEC" data-align="center"><span><?= _('MEC') ?></span></th>
							<th data-column-id="Estatus" data-align="center"><span><?= _('Estatus') ?></span></th>
							<th data-formatter="acciones-" 	data-sortable="false"><span><?= _('Acciones') ?></span></th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>1</td>
							<td>14/09/2018</td>
							<td>Enero-Febrero</td>
							<td>Nombre del Negocio 1</td>
							<td>Prescencial y Correo</td>
							<td>1000</td>
							<td>4</td>
							<td>Inactiva</td>
							<td>
								<div class="actions popup">
									<div class="outsidehidden">
										<div class="popmenu fouroptins">
											<div data-toggle="modal" data-target="#contrato">
												<?= _('Editar')?>
											</div>
											<div data-toggle="modal" data-target="#escalar">
												<?= _('Eliminar')?>
											</div>
											<div data-toggle="modal" data-target="#cancelar">
												<?= _('Duplicar')?>

											</div>
											<div data-toggle="modal" data-target="#renovar">
												<?= _('Programar')?>
											</div>
										</div>
										</div>
									</div>
									<a href="#" class="btn btn-secondary" data-id="1" id="openmodal">
										<i class="fas fa-cogs"></i>
									</a>
								</div>
							</td>
						</tr>
						<tr>
							<td>1</td>
							<td>14/09/2018</td>
							<td>Enero-Febrero</td>
							<td>Nombre del Negocio 1</td>
							<td>Prescencial y Correo</td>
							<td>1000</td>
							<td>4</td>
							<td>Inactiva</td>
							<td>

							</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>


	<div id="nuevaCamp" class="modal fade" role="dialog">
		<div class="modal-dialog modal-lg modal-xl">
			<!-- Modal content-->
			<div class="modal-content">
				<div class="modal-header">
					<h4 class="modal-title">
						<?=_('Nueva Campaña')?>
					</h4>
					<button type="button" class="close" data-dismiss="modal">&times;</button>
				</div>
				<div class="modal-body">
					<form id="nueva-camp" class="scrollmodal">
						<div class="nuevacamp-top">
							<div id="nomcamp">
								<label class="col-form-label required">
									<?=_('Unidad de negocio')?>
								</label>
								<select class="form-control" id="uninegocio">
									<option>
										<?=_('Principal')?>
									</option>
									<option>
										<?=_('Plaza Universidad')?>
									</option>
									<option>
										<?=_('Centro')?>
									</option>
									<option>
										<?=_('Plaza Patria')?>
									</option>
									<option>
										<?=_('Calvillo')?>
									</option>
								</select>

								<label class="col-form-label required">
									<?=_('Nombre de la campaña')?>
								</label>
								<input class="form-control" type="text" placeholder="" required="" v-model="nombreCampana" required>
							</div>
							<div class="datcamp">
								<label class="col-form-label required">
									<?=_('Tipo de Campaña')?>
								</label>
								<label class="containerbx">
									<?=_('Prescencial')?>
									<input type="radio" name="tipo_campana" value="prescencial" checked>
									<span class="checkmark"></span>
								</label>
								<label class="containerbx">
									<?=_('Correo')?>
									<input type="radio" name="tipo_campana" value="correo">
									<span class="checkmark"></span>
								</label>

								<label class="col-form-label required">
									<?=_('Cantidad de Encuestas')?>
								</label>
								<input class="form-control form-sml" type="text" placeholder="10" required="" v-model="cantidad_encuestas" required>
								<span class="info_extra_sml"> <?=_('Clientes:')?> 4553 - 10  = 4543 </span>
							</div>
						</div>

						<hr>

						<div class="nuevacamp-bot">
								<ul class="meclist">
									<li>
										<div class="mechead">
											<span class="titulo_MEC"><?=_('MEC/Reservación')?></span>
											<i class="fas fa-angle-down"></i>
										</div>
										<div class="mecbody">
											<label class="containercheck">Momento de verdad 1
												<input type="checkbox" >
												<span class="checkmarkcheck"></span>
											</label>
											<label class="containercheck">Momento de verdad 1
												<input type="checkbox" >
												<span class="checkmarkcheck"></span>
											</label>
											<label class="containercheck">Momento de verdad 1
												<input type="checkbox" >
												<span class="checkmarkcheck"></span>
											</label>
											<label class="containercheck">Momento de verdad 1
												<input type="checkbox" >
												<span class="checkmarkcheck"></span>
											</label>
											<label class="containercheck">Momento de verdad 1
												<input type="checkbox">
												<span class="checkmarkcheck"></span>
											</label>
											<label class="containercheck">Momento de verdad 1
												<input type="checkbox">
												<span class="checkmarkcheck"></span>
											</label>
											<label class="containercheck">Momento de verdad 1
												<input type="checkbox">
												<span class="checkmarkcheck"></span>
											</label>
										</div>
										<div class="mecfoot">
											<button type="button" class="btn btn-link btn-openmail"><?php echo _('Envianos una sugerencia') ?></button>
											<div class="mecmail">
												<form>
													<div class="form-group">
														<label for="mailSugerencia"><?=_('Sugerencia')?></label>
														<textarea class="form-control" id="mailSugerencia" rows="3" required></textarea>
													</div>
														<button type="button" class="btn btn-success btn-sm">
															<?php echo _('Enviar') ?></button>
												</form>
											</div>
										</div>

									</li>

									<li>
										<div class="mechead">
											<span class="titulo_MEC"><?=_('MEC/Reservación')?></span>
											<i class="fas fa-angle-down"></i>
										</div>
										<div class="mecbody">
											<label class="containercheck">Momento de verdad 1
												<input type="checkbox" >
												<span class="checkmarkcheck"></span>
											</label>
											<label class="containercheck">Momento de verdad 1
												<input type="checkbox" >
												<span class="checkmarkcheck"></span>
											</label>
											<label class="containercheck">Momento de verdad 1
												<input type="checkbox" >
												<span class="checkmarkcheck"></span>
											</label>
											<label class="containercheck">Momento de verdad 1
												<input type="checkbox" >
												<span class="checkmarkcheck"></span>
											</label>
											<label class="containercheck">Momento de verdad 1
												<input type="checkbox">
												<span class="checkmarkcheck"></span>
											</label>
											<label class="containercheck">Momento de verdad 1
												<input type="checkbox">
												<span class="checkmarkcheck"></span>
											</label>
											<label class="containercheck">Momento de verdad 1
												<input type="checkbox">
												<span class="checkmarkcheck"></span>
											</label>
										</div>
										<div class="mecfoot">
											<button type="button" class="btn btn-link btn-openmail"><?php echo _('Envianos una sugerencia') ?></button>
											<div class="mecmail">
												<form>
													<div class="form-group">
														<label for="mailSugerencia"><?=_('Sugerencia')?></label>
														<textarea class="form-control" id="mailSugerencia" rows="3" required></textarea>
													</div>
														<button type="button" class="btn btn-success btn-sm">
															<?php echo _('Enviar') ?></button>
												</form>
											</div>
										</div>

									</li>
									<li>
										<div class="mechead">
											<span class="titulo_MEC"><?=_('MEC/Reservación')?></span>
											<i class="fas fa-angle-down"></i>
										</div>
										<div class="mecbody">
											<label class="containercheck">Momento de verdad 1
												<input type="checkbox" >
												<span class="checkmarkcheck"></span>
											</label>
											<label class="containercheck">Momento de verdad 1
												<input type="checkbox" >
												<span class="checkmarkcheck"></span>
											</label>
											<label class="containercheck">Momento de verdad 1
												<input type="checkbox" >
												<span class="checkmarkcheck"></span>
											</label>
											<label class="containercheck">Momento de verdad 1
												<input type="checkbox" >
												<span class="checkmarkcheck"></span>
											</label>
											<label class="containercheck">Momento de verdad 1
												<input type="checkbox">
												<span class="checkmarkcheck"></span>
											</label>
											<label class="containercheck">Momento de verdad 1
												<input type="checkbox">
												<span class="checkmarkcheck"></span>
											</label>
											<label class="containercheck">Momento de verdad 1
												<input type="checkbox">
												<span class="checkmarkcheck"></span>
											</label>
										</div>
										<div class="mecfoot">
											<button type="button" class="btn btn-link btn-openmail"><?php echo _('Envianos una sugerencia') ?></button>
											<div class="mecmail">
												<form>
													<div class="form-group">
														<label for="mailSugerencia"><?=_('Sugerencia')?></label>
														<textarea class="form-control" id="mailSugerencia" rows="3" required></textarea>
													</div>
														<button type="button" class="btn btn-success btn-sm">
															<?php echo _('Enviar') ?></button>
												</form>
											</div>
										</div>

									</li>

									<li>
										<div class="mechead">
											<span class="titulo_MEC"><?=_('MEC/Reservación')?></span>
											<i class="fas fa-angle-down"></i>
										</div>
										<div class="mecbody">
											<label class="containercheck">Momento de verdad 1
												<input type="checkbox" >
												<span class="checkmarkcheck"></span>
											</label>
											<label class="containercheck">Momento de verdad 1
												<input type="checkbox" >
												<span class="checkmarkcheck"></span>
											</label>
											<label class="containercheck">Momento de verdad 1
												<input type="checkbox" >
												<span class="checkmarkcheck"></span>
											</label>
											<label class="containercheck">Momento de verdad 1
												<input type="checkbox" >
												<span class="checkmarkcheck"></span>
											</label>
											<label class="containercheck">Momento de verdad 1
												<input type="checkbox">
												<span class="checkmarkcheck"></span>
											</label>
											<label class="containercheck">Momento de verdad 1
												<input type="checkbox">
												<span class="checkmarkcheck"></span>
											</label>
											<label class="containercheck">Momento de verdad 1
												<input type="checkbox">
												<span class="checkmarkcheck"></span>
											</label>
										</div>
										<div class="mecfoot">
											<button type="button" class="btn btn-link btn-openmail"><?php echo _('Envianos una sugerencia') ?></button>
											<div class="mecmail">
												<form>
													<div class="form-group">
														<label for="mailSugerencia"><?=_('Sugerencia')?></label>
														<textarea class="form-control" id="mailSugerencia" rows="3" required></textarea>
													</div>
														<button type="button" class="btn btn-success btn-sm">
															<?php echo _('Enviar') ?></button>
												</form>
											</div>
										</div>

									</li>

									<li>
										<div class="mechead">
											<span class="titulo_MEC"><?=_('MEC/Reservación')?></span>
											<i class="fas fa-angle-down"></i>
										</div>
										<div class="mecbody">
											<label class="containercheck">Momento de verdad 1
												<input type="checkbox" >
												<span class="checkmarkcheck"></span>
											</label>
											<label class="containercheck">Momento de verdad 1
												<input type="checkbox" >
												<span class="checkmarkcheck"></span>
											</label>
											<label class="containercheck">Momento de verdad 1
												<input type="checkbox" >
												<span class="checkmarkcheck"></span>
											</label>
											<label class="containercheck">Momento de verdad 1
												<input type="checkbox" >
												<span class="checkmarkcheck"></span>
											</label>
											<label class="containercheck">Momento de verdad 1
												<input type="checkbox">
												<span class="checkmarkcheck"></span>
											</label>
											<label class="containercheck">Momento de verdad 1
												<input type="checkbox">
												<span class="checkmarkcheck"></span>
											</label>
											<label class="containercheck">Momento de verdad 1
												<input type="checkbox">
												<span class="checkmarkcheck"></span>
											</label>
										</div>
										<div class="mecfoot">
											<button type="button" class="btn btn-link btn-openmail"><?php echo _('Envianos una sugerencia') ?></button>
											<div class="mecmail">
												<form>
													<div class="form-group">
														<label for="mailSugerencia"><?=_('Sugerencia')?></label>
														<textarea class="form-control" id="mailSugerencia" rows="3" required></textarea>
													</div>
														<button type="button" class="btn btn-success btn-sm">
															<?php echo _('Enviar') ?></button>
												</form>
											</div>
										</div>

									</li>

									<li>
										<div class="mechead">
											<span class="titulo_MEC"><?=_('MEC/Reservación')?></span>
											<i class="fas fa-angle-down"></i>
										</div>
										<div class="mecbody">
											<label class="containercheck">Momento de verdad 1
												<input type="checkbox" >
												<span class="checkmarkcheck"></span>
											</label>
											<label class="containercheck">Momento de verdad 1
												<input type="checkbox" >
												<span class="checkmarkcheck"></span>
											</label>
											<label class="containercheck">Momento de verdad 1
												<input type="checkbox" >
												<span class="checkmarkcheck"></span>
											</label>
											<label class="containercheck">Momento de verdad 1
												<input type="checkbox" >
												<span class="checkmarkcheck"></span>
											</label>
											<label class="containercheck">Momento de verdad 1
												<input type="checkbox">
												<span class="checkmarkcheck"></span>
											</label>
											<label class="containercheck">Momento de verdad 1
												<input type="checkbox">
												<span class="checkmarkcheck"></span>
											</label>
											<label class="containercheck">Momento de verdad 1
												<input type="checkbox">
												<span class="checkmarkcheck"></span>
											</label>
										</div>
										<div class="mecfoot">
											<button type="button" class="btn btn-link btn-openmail"><?php echo _('Envianos una sugerencia') ?></button>
											<div class="mecmail">
												<form>
													<div class="form-group">
														<label for="mailSugerencia"><?=_('Sugerencia')?></label>
														<textarea class="form-control" id="mailSugerencia" rows="3" required></textarea>
													</div>
														<button type="button" class="btn btn-success btn-sm">
															<?php echo _('Enviar') ?></button>
												</form>
											</div>
										</div>

									</li>
								</ul>
						</div>


						<div class="modal-footer">
							<button type="button" class="btn btn-primary" @click="#" data-dismiss="modal">
								<?php echo _('Guardar Campaña') ?></button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>

	<!-- <div id="enviar" class="modal fade" role="dialog">
		<div class="modal-dialog modal-lg">

			<div class="modal-content">
				<div class="modal-header">
					<h4 class="modal-title">
						<?=_('Enviar sugerencia de Momento de la Verdad')?>
					</h4>
					<button type="button" class="close" data-dismiss="modal">&times;</button>
				</div>
				<div class="modal-body">

				</div>
			</div>
		</div>
	</div> -->
