<div class="row">
	<div class="col-sm-12">
		<div class="page-title-box">
			<div class="btn-group float-right">
				<ol class="breadcrumb hide-phone p-0 m-0">
					<li class="breadcrumb-item">
						<a href="<?php echo site_url('dashboard'); ?>"><?php echo _('Inicio') ?></a>
					</li>
					<li class="breadcrumb-item">
						<a href="<?php echo site_url('dashboard/catalogos/'); ?>"><?php echo _('Catalogos') ?></a>
					</li>
					<li class="breadcrumb-item active">
						<?php echo _('Ciudades') ?>
					</li>
				</ol>
			</div>
			<h4 class="page-title"><?php echo _('Catalogo de Ciudades') ?></h4>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-12">
		<div class="card m-b-30">
			<div class="card-body">
				<h4><?php echo _('Catálogo de las ciudades de México (Estado / Municipio / Codigo Postal)') ?></h4>
				<hr>
				<div class="m-b-30">
					<button id="DeleteAll" type="button" class="btn btn-danger waves-effect waves-light m-r-10 m-b-10 pull-right" @click="Run($event)" data-url-borrar="<?php echo site_url('ajax/sistema/ciudades/deleteall'); ?>"><?php echo _('Eliminar') ?></button>
					<button data-toggle="modal" data-target="#cargamasiva" type="button" class="btn btn-success waves-effect waves-light m-r-10 m-b-10 pull-right" ><?php echo _('Carga masiva') ?></button>
					<button data-toggle="modal" data-target="#nuevo" type="button" class="btn btn-success waves-effect waves-light m-r-10 m-b-10 pull-right" ><?php echo _('Nuevo registro') ?></button>
				</div>
				<br>
				<hr>
				<table class="table table-condensed table-hover table-striped tabla-ajax" data-url="<?php echo site_url('ajax/sistema/ciudades'); ?>" data-url-editar="<?php echo site_url('ajax/sistema/ciudad/consulta'); ?>" data-url-borrar="<?php echo site_url('ajax/sistema/ciudad/eliminar'); ?>"  >
					<thead>
						<tr>
							<th data-column-id="id" data-type="numeric">id</th>
							<th data-column-id="Estado"><?php echo _('Estado') ?></th>
							<th data-column-id="Municipio"><?php echo _('Muncipio') ?></th>
							<th data-column-id="Colonia"><?php echo _('Colonia') ?></th>
							<th data-column-id="CodigoPostal" data-type="numeric"><?php echo _('Codigo Postal') ?></th>
							<th data-formatter="acciones" data-sortable="false"><?php echo _('Acciones') ?></th>
						</tr>
					</thead>
				</table>
				<a href="<?php echo site_url('dashboard/catalogos/enfoques/nuevo'); ?>">
				</a>
			</div>
		</div>
	</div>
	<!-- end col -->
</div>
<!-- end row -->
<div class="modal fade show modal-detalles" id="cargamasiva" tabindex="-1" role="dialog" v-bind="familia">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-body">
				<h6><?php echo _('Carga masiva') ?></h6>
				<hr>
				<form id="CargaMasiva" @submit.prevent="SendData('sistema/ciudades/cargamasiva',$event)" data-parsley-validate>
					<div class="form-group p-l-9  p-r-90">
						<input type="file" class="dropify" name="archivo" required>
					</div>
					<div class="modal-footer">
						<button type="submit" class="btn btn-primary float-right"><?php echo _('Guardar') ?></button>
						<button type="button" class="btn btn-default" data-dismiss="modal"><?php echo _('Cerrar') ?></button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

<div class="modal fade show modal-detalles" id="nuevo" tabindex="-1" role="dialog" v-bind="familia">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-body">
				<h6><?php echo _('Nuevo registro') ?></h6>
				<hr>
				<form class="form-ajax" data-url="sistema/ciudad/nuevo" data-parsley-validate>
					<div class="form-group row">
						<label class="col-sm-2 col-form-label required"><?php echo _('Estado') ?></label>
						<div class="col-sm-10">
							<input class="form-control" type="text" placeholder="" required="" name="datos[Estado]" value="">
						</div>
					</div>
					<div class="form-group row">
						<label class="col-sm-2 col-form-label required"><?php echo _('Municipio') ?></label>
						<div class="col-sm-10">
							<input class="form-control" type="text" placeholder="" required="" name="datos[Municipio]" value="">
						</div>
					</div>
					<div class="form-group row">
						<label class="col-sm-2 col-form-label required"><?php echo _('Colonia') ?></label>
						<div class="col-sm-10">
							<input class="form-control" type="text" placeholder="" required="" name="datos[Colonia]" value="">
						</div>
					</div>
					<div class="form-group row">
						<label class="col-sm-2 col-form-label required"><?php echo _('Codigo postal') ?></label>
						<div class="col-sm-10">
							<input class="form-control" type="text" placeholder="" required="" name="datos[CodigoPostal]" value="">
						</div>
					</div>
					<div class="modal-footer">
						<button type="submit" class="btn btn-primary float-right"><?php echo _('Guardar') ?></button>
						<button type="button" class="btn btn-default" data-dismiss="modal"><?php echo _('Cerrar') ?></button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

<div class="modal fade show modal-detalles" id="Editar" tabindex="-1" role="dialog">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-body">
				<h6><?php echo _('Editar Ciudad') ?></h6>
				<hr>
				<form class="form-ajax" data-url="sistema/ciudad/editar" data-parsley-validate>
					<div class="form-group row">
						<label class="col-sm-2 col-form-label required"><?php echo _('Estado') ?></label>
						<div class="col-sm-10">
							<input class="form-control" type="text" placeholder="" required="" name="datos[Estado]" :value="datos.Estado">
						</div>
					</div>
					<div class="form-group row">
						<label class="col-sm-2 col-form-label required"><?php echo _('Municipio') ?></label>
						<div class="col-sm-10">
							<input class="form-control" type="text" placeholder="" required="" name="datos[Municipio]" :value="datos.Municipio">
						</div>
					</div>
					<div class="form-group row">
						<label class="col-sm-2 col-form-label required"><?php echo _('Colonia') ?></label>
						<div class="col-sm-10">
							<input class="form-control" type="text" placeholder="" required="" name="datos[Colonia]" :value="datos.Colonia">
						</div>
					</div>
					<div class="form-group row">
						<label class="col-sm-2 col-form-label required"><?php echo _('Codigo postal') ?></label>
						<div class="col-sm-10">
							<input class="form-control" type="text" placeholder="" required="" name="datos[CodigoPostal]" :value="datos.CodigoPostal">
						</div>
					</div>
					<div class="modal-footer">
						<button type="submit" class="btn btn-primary float-right"><?php echo _('Guardar') ?></button>
						<button type="button" class="btn btn-default" data-dismiss="modal"><?php echo _('Cerrar') ?></button>
					</div>
					<input type="hidden" name="id" :value="datos.idCatalogoCiudad" />
				</form>
			</div>
		</div>
	</div>
</div>
