<?php global $sidebar_menu, $site_url, $ruta; ?>
<div class="row">
	<div class="col-sm-12">
		<div class="page-title-box">
			<div class="btn-group float-right">
				<ol class="breadcrumb hide-phone p-0 m-0">
					<li class="breadcrumb-item">
						<a href="<?php echo site_url('dashbord'); ?>"><?php echo _('Inicio') ?></a>
					</li>
					<li class="breadcrumb-item active">
						<?php echo _('Perfil') ?>
					</li>
				</ol>
			</div>
			<h4 class="page-title"><?php echo _('Datos personales') ?></h4>
		</div>
	</div>
</div>
<div class="row">
	<div class="col-12">
		<div class="card m-b-30">
			<div class="card-body">
				<h4><?php echo _('Datos Personales') ?></h4>
				<hr>
				<div class="container bootstrap snippet">
					<div class="row">
						<div class="col-sm-3">
							<!--left col-->
							<div class="text-center photo">
								<img src="http://ssl.gstatic.com/accounts/ui/avatar_2x.png" class="avatar rounded-circle img-thumbnail" alt="avatar">
								<!-- <h6><?php echo _('Cargar Foto...') ?></h6> -->
								<h6>Arrastra un archivo o da click en la imagen</h6>
								<input type="file" class=" dropify text-center center-block file-upload">
							</div><br>
						</div>
						<!--/col-3-->
						<div class="col-sm-9">
							<div class="tab-content">
								<div class="tab-pane active" id="UserPage">
									<form class="form" method="post">
										<div class="form-group name">
											<div class="col-xs-6">
												<label for="first_name">
													<label class="col-form-label required"><?php echo _('Nombre') ?></label>
												</label>
												<input type="text" class="form-control" name="datos[Nombre]" :value="datos.Nombre">
											</div>
										</div>
										<div class="form-group">
											<div class="col-xs-6">
												<label for="last_name">
													<label class="col-form-label required"><?php echo _('Apellido Paterno') ?></label>
												</label>
												<input type="text" class="form-control" name="datos[ApPaterno]" :value="datos.ApPaterno">
											</div>
										</div>
										<div class="form-group">
											<div class="col-xs-6">
												<label for="last_name">
													<label class="col-form-label required"><?php echo _('Apellido Materno') ?></label>
												</label>
												<input type="text" class="form-control" name="datos[ApMaterno]" :value="datos.ApMaterno">
											</div>
										</div>
										<div class="form-group">
											<div class="col-xs-6">
												<label for="last_name">
													<label class="col-form-label required"><?php echo _('Empresa') ?></label>
												</label>
												<input type="text" class="form-control" name="datos[Emrpresa]" :value="datos.Empresa">
											</div>
										</div>
										<div class="form-group">
											<div class="col-xs-6">
												<label for="last_name">
													<label class="col-form-label required"><?php echo _('Cargo') ?></label>
												</label>
												<input type="text" class="form-control" name="datos[cargo]" :value="datos.Cargo">
											</div>
										</div>
										<div class="form-group">
											<div class="col-xs-6">
												<label for="phone">
													<label class="col-form-label required"><?php echo _('Telefono') ?></label>
												</label>
												<input type="text" class="form-control" name="datos[telefono]" :value="datos.Telefono">
											</div>
										</div>
										<div class="form-group">
											<div class="col-xs-6">
												<label for="email">
													<label class="col-form-label required"><?php echo _('Email') ?></label>
												</label>
												<input type="email" class="form-control" name="data[email]" :value="datos.email">
											</div>
										</div>
										<div class="form-group button">
											<div class="col-xs-12">
												<br>
												<button class="btn btn-lg btn-success" type="submit"><i class="glyphicon glyphicon-ok-sign"></i><?php echo _('Guardar') ?></button>
											</div>
										</div>
										<input type="hidden" name="id" vmodel='id' :value="id = <?=tk_id()?>">
									</form>
								</div>
							</div>
							<!--/tab-content-->
						</div>
						<!--/col-9-->
					</div>
				</div>
			</div>
		</div>
		<!-- end col -->
	</div>
	<!-- end row -->
