<div class="row">
	<div class="col-sm-12">
		<div class="page-title-box">
			<div class="btn-group float-right">
				<ol class="breadcrumb hide-phone p-0 m-0">
					<li class="breadcrumb-item">
						<a href="<?= site_url('dashboard') ?>">
							<?= _('Inicio')?></a>
					</li>
					<li class="breadcrumb-item">
						<a href="<?= site_url('dashboard/unidades/') ?>">
							<?= _('Unidades')?></a>
					</li>
					<li class="breadcrumb-item active">
						<?= _('Vinculación de Unidades')?>
					</li>
				</ol>
			</div>
			<h4 class="page-title">
				<?= _('Vinculación de Unidades de Negocio')?>
			</h4>
		</div>
	</div>
</div>


<div class="row">
	<div class="col-12">
		<div class="card">
			<div class="card-body">

				<h4 class="card-title">
					<?php echo _('Vinculación de Unidades de Negocio') ?>
				</h4>
				<hr>
				<div class="m-b-30">
					<button class="btn btn-success waves-effect waves-light m-r-10 m-b-10 pull-right" data-toggle="modal" data-target="#nuevoAdmin">
						<i class="fas fa-plus-circle"></i>
						<?php echo _('Agregar') ?>
					</button>
				</div>
				<br>
				<hr>

				<table class="table table-condensed table-hover table-striped tabla-ajax" data-url="<?= site_url('ajax/sistema/vinculacion-unidad'); ?>" data-url-editar="#" data-url-borrar="<?= site_url('ajax/sistema/vinculacion-unidad/eliminar'); ?>">
					<thead>
						<tr>
							<th data-align="center" data-column-id="id" data-type="numeric">id</th>
							<th data-align="center" data-column-id="NombreUnidad">
								<?php echo _('Unidad negocio') ?>
							</th>
							<th data-align="center" data-column-id="Tipo">
								<?php echo _('Tipo Unidad') ?>
							</th>
							<th data-align="center" data-column-id="NombreAdministrador">
								<?php echo _('Nombre Administrador') ?>
							</th>
							<th data-formatter="acciones-eliminar-only" data-sortable="false">
								<?php echo _('Acciones') ?>
							</th>
						</tr>
					</thead>
				</table>
			</div>
		</div>
	</div>
</div>

<div id="nuevoAdmin" class="modal fade" role="dialog">
	<div class="modal-dialog modal-lg">
		<!-- Modal content-->
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title">
					<?=_('Agregar Administrador')?>
				</h4>
				<button type="button" class="close" data-dismiss="modal">&times;</button>
			</div>
			<div class="modal-body" >
				<form id="lista-uni"class="form-ajax" data-url="sistema/vinculacion-unidad/nuevo" data-parsley-validate>
					<div id="chunit">
						<label class="col-form-label required">
							<?=_('Administrador de la Unidad de Negocio')?>
						</label>
						<select class="custom-select chain-select" data-url="<?= site_url('ajax/sistema/generales/administradores'); ?>" name="datos[idAdmin]" id="adminegocio">
						</select>
						<label class="col-form-label required">
							<?=_('Unidad de negocio')?>
						</label>
						<select class="custom-select chain-select" data-url="<?= site_url('ajax/sistema/generales/unidades'); ?>" data-parent="#adminegocio" name="datos[idUnidad]" id="uninegocio">
						</select>
					</div>
					<div class="modal-footer">
						<button type="submit" class="btn btn-primary">
							<?php echo _('Guardar Administrador') ?></button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
