<div class="row">
	<div class="col-sm-12">
		<div class="page-title-box">
			<div class="btn-group float-right">
				<ol class="breadcrumb hide-phone p-0 m-0">
					<li class="breadcrumb-item active">
						<?php echo _('Inicio') ?>
					</li>
				</ol>
			</div>
			<h4 class="page-title"><?php echo _('Inicio') ?></h4>
		</div>
		<div class="card">
		</div>
	</div>
</div>
<!-- end page title end breadcrumb -->
